# Use postgres/example user/password credentials
version: "3.8"

services:
  db:
    image: postgres:14-bullseye
    restart: "on-failure"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: golang-samzhangjy

  adminer:
    image: adminer:4
    restart: "on-failure"
    ports:
      - 8080:8080

volumes:
  node_modules:
