####
GET http://0.0.0.0:5010


#### Get JWT
GET http://0.0.0.0:5010/get-jwt


#### GET JWKs
GET http://0.0.0.0:5010/wellknown/jwks.json

#### Access to protected page
GET http://0.0.0.0:5010/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMC4wLjAuMDo1MDEwIiwiYXVkIjpbImh0dHA6Ly8wLjAuMC4wOjUwMTEiXSwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3MDgzMzM4MzEsImV4cCI6MTcwODQyMDIzMX0.RoVku13ZnJmXJLiRjWx4eEPaxATzVRctcxnpYj9szT3JQ3fSTSo-uYekfi1u3k022WREaP3oRyScVFUQrN4gVabph6F7TZPzrf0QIhMt1UMu1JZj83hdChm6cGFFZDChP9mG2_yjJ2FOBq3Mu4grvJ4C8uX-22dK58PF-TJjon4kURn2y_klMd0lZ0rKWyQBWNW8hscafwEGBAm-YDv257scpRVoGe8GL5lDNNLvLqk3po1hTvlDrnEi5UEpgw6TL0RnBi9wlKs8q7VbZo4AmMJT0q6Vi2ISJ62sCAeinWwsdjxm2XegNO6y7rYgIHZ0VgA-ccLwlfJSzd3gn4TpmQ


####
GET http://0.0.0.0:5011

### Client required token
GET http://0.0.0.0:5011/required-token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMC4wLjAuMDo1MDEwIiwiYXVkIjpbImh0dHA6Ly8wLjAuMC4wOjUwMTEiXSwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3MDgzMzM4MzEsImV4cCI6MTcwODQyMDIzMX0.RoVku13ZnJmXJLiRjWx4eEPaxATzVRctcxnpYj9szT3JQ3fSTSo-uYekfi1u3k022WREaP3oRyScVFUQrN4gVabph6F7TZPzrf0QIhMt1UMu1JZj83hdChm6cGFFZDChP9mG2_yjJ2FOBq3Mu4grvJ4C8uX-22dK58PF-TJjon4kURn2y_klMd0lZ0rKWyQBWNW8hscafwEGBAm-YDv257scpRVoGe8GL5lDNNLvLqk3po1hTvlDrnEi5UEpgw6TL0RnBi9wlKs8q7VbZo4AmMJT0q6Vi2ISJ62sCAeinWwsdjxm2XegNO6y7rYgIHZ0VgA-ccLwlfJSzd3gn4TpmQ


### Client required token
POST http://0.0.0.0:5011/parsing-jwt
Content-Type: application/json

{
    "token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMC4wLjAuMDo1MDEwIiwiYXVkIjpbImh0dHA6Ly8wLjAuMC4wOjUwMTEiXSwibmFtZSI6IkpvaG4gRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsInJvbGVzIjpbImFkbWluIiwidXNlciJdLCJpYXQiOjE3MDgzMzM4MzEsImV4cCI6MTcwODQyMDIzMX0.RoVku13ZnJmXJLiRjWx4eEPaxATzVRctcxnpYj9szT3JQ3fSTSo-uYekfi1u3k022WREaP3oRyScVFUQrN4gVabph6F7TZPzrf0QIhMt1UMu1JZj83hdChm6cGFFZDChP9mG2_yjJ2FOBq3Mu4grvJ4C8uX-22dK58PF-TJjon4kURn2y_klMd0lZ0rKWyQBWNW8hscafwEGBAm-YDv257scpRVoGe8GL5lDNNLvLqk3po1hTvlDrnEi5UEpgw6TL0RnBi9wlKs8q7VbZo4AmMJT0q6Vi2ISJ62sCAeinWwsdjxm2XegNO6y7rYgIHZ0VgA-ccLwlfJSzd3gn4TpmQ"
}
