import * as Yup from "yup";

export const MarginModelScalarFieldEnumSchema = Yup.mixed().oneOf([
  "id",
  "createdAt",
  "updatedAt",
  "productCode",
  "isActive",
  "productType",
  "productNameLabel",
  "productNameValue",
  "remarksLabel",
  "remarksValue",
  "priceLevel1Label",
  "priceLevel1Value",
  "priceLevel2Label",
  "priceLevel2Value",
  "priceLevel3Label",
  "priceLevel3Value",
  "priceLevel4Label",
  "priceLevel4Value",
  "priceLevel5Label",
  "priceLevel5Value",
  "priceLevel6Label",
  "priceLevel6Value",
  "priceLevel7Label",
  "priceLevel7Value",
  "priceLevel8Label",
  "priceLevel8Value",
  "priceLevel9Label",
  "priceLevel9Value",
  "priceLevel10Label",
  "priceLevel10Value",
  "priceLevel11Label",
  "priceLevel11Value",
]);
