version: "3.1"

services:
  db:
    image: postgres:15.4-bullseye
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Password

  adminer:
    image: adminer:4.8.1
    restart: no
    ports:
      - 8080:8080
