GET http://localhost:3001


### create post


POST http://localhost:3001/posts
content-type: application/json

{
    "title": "sample",
    "content": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### get posts


GET http://localhost:3001/posts

### get post

GET http://localhost:3001/posts/1999

### update
PATCH http://localhost:3001/posts/1
content-type: application/json

{
    "title": "sample-000",
    "content": "Wed, 21 Oct 2015 18:27:50 GMT -000"
}

### delete

DELETE  http://localhost:3001/posts/1
