version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "java-lambda-s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10xn6zuxe2jit"
s3_prefix = "java-lambda-s3"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
