export {
  MarginModelObject,
  MarginModelIdFieldObject,
  MarginModelCreatedAtFieldObject,
  MarginModelUpdatedAtFieldObject,
  MarginModelProductCodeFieldObject,
  MarginModelIsActiveFieldObject,
  MarginModelProductTypeFieldObject,
  MarginModelProductNameLabelFieldObject,
  MarginModelProductNameValueFieldObject,
  MarginModelRemarksLabelFieldObject,
  MarginModelRemarksValueFieldObject,
  MarginModelPriceLevel1LabelFieldObject,
  MarginModelPriceLevel1ValueFieldObject,
  MarginModelPriceLevel2LabelFieldObject,
  MarginModelPriceLevel2ValueFieldObject,
  MarginModelPriceLevel3LabelFieldObject,
  MarginModelPriceLevel3ValueFieldObject,
  MarginModelPriceLevel4LabelFieldObject,
  MarginModelPriceLevel4ValueFieldObject,
  MarginModelPriceLevel5LabelFieldObject,
  MarginModelPriceLevel5ValueFieldObject,
  MarginModelPriceLevel6LabelFieldObject,
  MarginModelPriceLevel6ValueFieldObject,
  MarginModelPriceLevel7LabelFieldObject,
  MarginModelPriceLevel7ValueFieldObject,
  MarginModelPriceLevel8LabelFieldObject,
  MarginModelPriceLevel8ValueFieldObject,
  MarginModelPriceLevel9LabelFieldObject,
  MarginModelPriceLevel9ValueFieldObject,
  MarginModelPriceLevel10LabelFieldObject,
  MarginModelPriceLevel10ValueFieldObject,
  MarginModelPriceLevel11LabelFieldObject,
  MarginModelPriceLevel11ValueFieldObject,
  MarginModelHardwareFieldObject
} from './object.base';
export {
  createManyMarginModelMutation,
  createOneMarginModelMutation,
  deleteManyMarginModelMutation,
  deleteOneMarginModelMutation,
  updateManyMarginModelMutation,
  updateOneMarginModelMutation,
  upsertOneMarginModelMutation,
  createManyMarginModelMutationObject,
  createOneMarginModelMutationObject,
  deleteManyMarginModelMutationObject,
  deleteOneMarginModelMutationObject,
  updateManyMarginModelMutationObject,
  updateOneMarginModelMutationObject,
  upsertOneMarginModelMutationObject
} from './mutations';
export {
  findFirstMarginModelQuery,
  findManyMarginModelQuery,
  countMarginModelQuery,
  findUniqueMarginModelQuery,
  findFirstMarginModelQueryObject,
  findManyMarginModelQueryObject,
  countMarginModelQueryObject,
  findUniqueMarginModelQueryObject
} from './queries';
